### ISSUE TITLE
Parquet files not downloaded correctly during git clone

### ISSUE THREAD

**Issue by MattsonCam** [WayScience/nf1_cellpainting_data#13]
During a git clone, the Parquet files do not seem to download correctly. There seems to be some information loss in the process.

**Comment by jenna-tomkinson** [comment]
@MattsonCam 

Thank you for the inquiry. Looks like this is happening because we are using [`git lfs`](https://git-lfs.com/) to store these larger files onto GitHub. This documentation was added in PR #11 so I am closing this issue.
