### ISSUE TITLE
Missing Metadata column in plate 5 feature selected data

### ISSUE THREAD

**Issue by MattsonCam** [WayScience/nf1_cellpainting_data#32]
In the [plate 5 feature selected data](https://github.com/WayScience/nf1_cellpainting_data/blob/main/3.processing_features/data/single_cell_profiles/Plate_5_sc_feature_selected.parquet) there are 62 cells without a "Metadata_ImageNumber" value. Possibly related to CytoTable?

**Comment by jenna-tomkinson** [comment]
I am going to put this as closed since this was directly related to a CytoTable issue that included rows where a well either failed QC or had no segmentations.
