### ISSUE TITLE
Mint DOI GitHub/Zenodo integration

### ISSUE THREAD

**Issue by gwaybio** [WayScience/nf1_cellpainting_data#50]
Perform zenodo integration to mint DOI for this repo.

Prior to doing this, we need to accomplish the following:

- [x] Add plate 5 to Figshare
- [x] Add DOI links to each Figshare plate (probably in a table, describing each plate?) in the README
- [x] Review repo and perform any gardening/weed pulling
- [x] Mint Zenodo DOI

**Comment by jenna-tomkinson** [comment]
This repo is ready for minting after PR #52! :tada:
