### ISSUE TITLE
Pip error during CellProfiler Install

### ISSUE THREAD

**Issue by MattsonCam** [WayScience/nf1_cellpainting_data#6]
On Popos, the `conda env create -f nf1_cellpainting_env.yml` produces an error during the pip installation of the CellProfiler as shown in the attached screenshot:
![image](https://user-images.githubusercontent.com/92554334/229881166-1b3da9b1-4806-447b-9850-566e30101935.png)

**Comment by jenna-tomkinson** [comment]
It looks like the solution to their error was making sure that this command was run on the computer before creating the environment:

```bash
sudo apt-get install libmysqlclient-dev
```

Having this installed will fix this issue with the `mysqlclient` error.

I am not sure if this issue happens on Mac as it looks like it worked on my end, but if this issue pops up again on Mac, then this issue can be reopened.
